### ISSUE TITLE
Action fails if docker not installed

### ISSUE THREAD

**Issue by samuelallan72** [canonical/setup-lxd#19]
This is the output from a recent action run:

```
Run canonical/setup-lxd@v0.1.1
Run if ! snap info lxd | grep "installed"; then
installed:          5.0.3-80aeff7             (29353)  81MB -
Run sudo lxd waitready
Run sudo snap set lxd daemon.group=adm
2024-08-05T00:47:00Z INFO Waiting for "snap.lxd.daemon.service" to stop.
Restarted.
Run set -x
  set -x
  sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
  sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
+ sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
iptables: No chain/target/match by that name.
Error: Process completed with exit code 1.
```

This action should work regardless of whether docker is installed or not.

**Comment by camrionnvmff** [comment]
The error message shows that there is a problem running the iptables command, specifically because the DOCKER-USER chain cannot be found. This issue usually occurs when Docker is not installed or started, as the DOCKER-USER chain is automatically created by Docker.

To solve this problem,
Confirm Docker is installed and running: Before executing these commands, make sure Docker is installed and running. You can check the status of Docker by using the following command:
sudo systemctl status docker
Install Docker: If Docker is not installed, you can install it using the following command:
sudo apt-get update
sudo apt-get install docker.io
sudo systemctl start docker
sudo systemctl enable docker
Confirm the existence of DOCKER-USER chain: After Docker starts, confirm whether the DOCKER-USER chain exists:
sudo iptables -L DOCKER-USER
If there are no issues with these steps, then your script should be able to run normally. If there are still issues, it is recommended to phase out Docker and deploy the environment using the 2024 tool Servbay

**Comment by Pjack** [comment]
> The error message shows that there is a problem running the iptables command, specifically because the DOCKER-USER chain cannot be found. This issue usually occurs when Docker is not installed or started, as the DOCKER-USER chain is automatically created by Docker.
> 
> To solve this problem, Confirm Docker is installed and running: Before executing these commands, make sure Docker is installed and running. You can check the status of Docker by using the following command: sudo systemctl status docker Install Docker: If Docker is not installed, you can install it using the following command: sudo apt-get update sudo apt-get install docker.io sudo systemctl start docker sudo systemctl enable docker Confirm the existence of DOCKER-USER chain: After Docker starts, confirm whether the DOCKER-USER chain exists: sudo iptables -L DOCKER-USER If there are no issues with these steps, then your script should be able to run normally. If there are still issues, it is recommended to phase out Docker and deploy the environment using the 2024 tool Servbay

I don't understand why we need to install Docker before using LXD. There shouldn't be any dependency between the two.

**Comment by samuelallan72** [comment]
@Pjack , @camrionnvmff's comment is AI generated spam; I've reported it. :)
